# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^tests/integration|\.patch|^nix/_sources
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md"
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: Check python (ruff)
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: poetry run ruff check --force-exclude
        args:
          [--output-format=full, --fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Format python (ruff)
        language: system
        types_or: [python, pyi]
        require_serial: true
        entry: poetry run ruff format --force-exclude

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        name: Check vulture

  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-actions
        name: Check Github actions
      - id: check-github-workflows
        name: Check Github workflows
